In [1]:
import numpy as np
log = np.log
array = np.array
from scipy.optimize import root


In [64]:
MWs_l = np.array([44.01, 61.08, 18.02]) / 1000  # kg/mol

def liquid_density(Tl, x):

    x_CO2, x_MEA, x_H2O = x

    MWT_l = sum([x[i] * MWs_l[i] for i in range(len(x))])

    a1, b1, c1 = [-5.35162e-7, -4.51417e-4, 1.19451]
    a2, b2, c2 = [-3.2484e-6, 0.00165, 0.793]

    V_MEA = MWs_l[1]*1000 / (a1 * Tl ** 2 + b1 * Tl + c1)  # mL/mol
    V_H2O = MWs_l[2]*1000 / (a2 * Tl ** 2 + b2 * Tl + c2)   # mL/mol

    a, b, c, d, e = 10.57920122, -2.020494157, 3.15067933, 192.0126008, -695.3848617


    V_CO2 = a + (b + c * x_MEA) * x_MEA * x_H2O + (d + e * x_MEA) * x_MEA * x_CO2

    V_l = V_CO2 * x_CO2 + x_MEA * V_MEA + x_H2O * V_H2O # Liquid Molar Volume (mL/mol)
    V_l = V_l*1e-6  # Liquid Molar Volume (mL/mol --> m3/mol)

    rho_mol_l = V_l**-1  # Liquid Molar Density (m3/mol --> mol/m3)

    return rho_mol_l

def solve_ChemEQ_log(α, w_MEA, Tl):
    
    MW_CO2 = 44.01/1000
    MW_MEA = 61.08/1000
    MW_H2O = 18.02/1000
    
    def get_x(α, w_MEA):
    
        x_MEA = ((1 + α + (MW_MEA/MW_H2O))*(1-w_MEA)/w_MEA)**-1
        x_CO2 = x_MEA*α
        x_H2O = 1 - x_CO2 - x_MEA
    
        return [x_CO2, x_MEA, x_H2O]
    
    x = get_x(α, w_MEA)
    
    rho_mol_l = liquid_density(Tl, x)
    
    Cl = [x[i] * rho_mol_l for i in range(len(x))]
    
    Cl_MEA_t = Cl[1]
    Cl_H2O_t = Cl[2]
 
    C1 = 132.889, -13445.9, -22.4773, 0
    C2 = 231.465, - 12092.10, - 36.7816, 0
    C3 = 216.049, -12431.70, -35.4819, 0
    C4 = .79960, -8084.81, 0, 0
    C5 = 1.282562, -3456.179, 0, - 0.007484
    

    def f_logK(C, T):
        C1, C2, C3, C4 = C
        return np.exp(C1 + C2 / T + C3 * log(T) + C4 * T)

    K1 = f_logK(C1, Tl)
    K2 = f_logK(C2, Tl)

    K3 = f_logK(C3, Tl)
    K4 = f_logK(C4, Tl)
    K5 = f_logK(C5, Tl)
    
    scale = 1e6

    def f(z):
        Cl_CO2, Cl_MEA, Cl_MEAH, Cl_MEACOO, Cl_HCO3, Cl_H3O, Cl_OH, Cl_CO3 = z

        # Kee1 = log(Cl_H3O) + log(Cl_OH)
        # Kee2 = log(Cl_HCO3)+log(Cl_HCO3) - log(Cl_HCO3)
        # Kee3 = log(Cl_H3O) +log(Cl_CO3) - log(Cl_HCO3)
        # Kee4 = log(Cl_HCO3)+log(Cl_MEA) - log(Cl_MEACOO)
        # Kee5 = log(Cl_H3O)+log(Cl_MEA) - log(Cl_MEAH)
        
        Kee1 = Cl_H3O*Cl_OH
        Kee2 = Cl_HCO3*Cl_HCO3 / Cl_HCO3
        Kee3 = Cl_H3O*Cl_CO3 / Cl_HCO3
        Kee4 = Cl_HCO3*Cl_MEA / Cl_MEACOO
        Kee5 = Cl_H3O*Cl_MEA / Cl_MEAH

        
        eq1 = (Kee1 - K1)*scale
        eq2 = (Kee2 - K2)*scale
        eq3 = (Kee3 - K3)*scale
        eq4 = (Kee4 - K4)*scale
        eq5 = (Kee5 - K5)*scale
        eq6 = Cl_MEA_t - (Cl_MEA + Cl_MEAH - Cl_MEACOO)
        eq7 = Cl_MEA_t*α - (Cl_CO2 - Cl_HCO3 + Cl_CO3 + Cl_MEACOO)
        eq8 = Cl_H3O + Cl_MEAH - Cl_MEACOO - Cl_HCO3 - 2*Cl_CO3 - Cl_OH

        eqs = array([eq1, eq2, eq3, eq4, eq5, eq6, eq7, eq8])
        float_formatter = "{:.4f}".format
        np.set_printoptions(formatter={'float_kind':float_formatter})
        # print(z)
        # print(eqs)
        
        return eqs

    guesses = array([0.1, 4000, 2000, 2000, 50,  10, .01, .01])
    result = root(f, guesses)
    Cl =  array(result.x)
    print(Cl/sum(Cl))
    Cl_CO2, Cl_MEA = Cl[:2]
    x = ([Cl[0], Cl[1], Cl_H2O_t])/np.sum([Cl[0], Cl[1], Cl_H2O_t])
    
    print(x)
    print(result.success)

    return x

x = solve_ChemEQ_log(.3004, .30, 393.15)
x = x[:3]/sum(x[:3])
print(x)


[-0.5264 0.2958 0.6153 0.6153 0.0000 0.0000 -0.0000 0.0000]
[-0.2008 0.1128 1.0879]
True
[-0.2008 0.1128 1.0879]
